package org.eclipse.tractusx.edc.spi.audit.types;

public enum AuditEventName {
    // Contract Definition Events
    CONTRACT_DEFINITION_CREATED,
    CONTRACT_DEFINITION_UPDATED,

    // Contract Negotiation Events
    CONTRACT_NEGOTIATION_INITIATED,
    CONTRACT_NEGOTIATION_REQUESTED,
    CONTRACT_NEGOTIATION_ACCEPTED,
    CONTRACT_NEGOTIATION_AGREED,
    CONTRACT_NEGOTIATION_VERIFIED,
    CONTRACT_NEGOTIATION_TERMINATED,
    CONTRACT_NEGOTIATION_OFFERED,
    CONTRACT_NEGOTIATION_FINALIZED,

    // Transfer Process Events
    TRANSFER_PROCESS_STARTED,
    TRANSFER_PROCESS_PROVISIONED,
    TRANSFER_PROCESS_REQUESTED,
    TRANSFER_PROCESS_TERMINATED,
    TRANSFER_PROCESS_INITIATED,
    TRANSFER_PROCESS_SUSPENDED,
    TRANSFER_PROCESS_PROVISIONING_REQUESTED,
    TRANSFER_PROCESS_DEPROVISIONING_REQUESTED,

    // Asset Events
    ASSET_CREATED,
    ASSET_UPDATED,
    ASSET_DELETED,

    // Policy Definition Events
    POLICY_DEFINITION_CREATED,
    POLICY_DEFINITION_UPDATED,
    POLICY_DEFINITION_DELETED,

    // Contract Request / Validation / Offer
    CONTRACT_REQUEST_SENT,
    CONTRACT_REQUEST_RECEIVED,
    CONTRACT_VALIDATION_PASSED,
    CONTRACT_VALIDATION_FAILED,
    CONTRACT_OFFER_CREATED,
    CONTRACT_OFFER_PUBLISHED,

    // Contract Agreement Events
    CONTRACT_AGREEMENT_CREATED,
    CONTRACT_AGREEMENT_VERIFIED,

    // Security/Authentication Events
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAILURE,
    ADMIN_CONFIGURATION_CHANGED,
    SYSTEM_ERROR,
    SYSTEM_STARTUP,
    SYSTEM_SHUTDOWN,

    // Catalog / Participant
    CATALOG_REQUESTED,
    CATALOG_PUBLISHED,
    PARTICIPANT_ONBOARDED,
    PARTICIPANT_OFFBOARDED
}
